-- 강남구에 위치한 가게 별 결제 횟수를 구하는 문제

-- 코드를 입력하세요
SELECT MERCHANTS.ID AS '가게 ID', MERCHANTS.NAME, COUNT(*) AS '결제 횟수'
FROM CARD_USAGES
JOIN MERCHANTS
ON CARD_USAGES.MERCHANT_ID = MERCHANTS.ID
WHERE CATEGORY = '결제' AND (NAME LIKE '%강남%' OR NAME LIKE '%논현%')
GROUP BY CARD_USAGES.MERCHANT_ID
ORDER BY MERCHANTS.ID;